


import java.util.Random;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Monty_Hall_Problem.java
 *
 * Created on Jan 1, 2013, 10:28:52 PM
 */

/**
 *
 * @author Gyanendra
 */
public class Monty_Hall_Problem extends javax.swing.JFrame {

    /** Creates new form Monty_Hall_Problem */
    public Monty_Hall_Problem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jt = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("qm.png"))); // NOI18N
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("qm.png"))); // NOI18N
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("qm.png"))); // NOI18N
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });

        jb1.setText("Play");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Gyani Productions");

        jButton1.setText("Iterate To Show Changing Helps");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jt, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb1)
                                .addGap(86, 86, 86)))))
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(605, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int count = 0;
int r = 0 ;
int r1 = 0 ;
int r2 = 0 ;
int r3 = 0 ;
    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
count = count+ 1 ;
if (count % 3 == 0){
l1.setIcon(new ImageIcon(getClass().getResource("qm.png")));
l3.setIcon(new ImageIcon(getClass().getResource("qm.png")));
l2.setIcon(new ImageIcon(getClass().getResource("qm.png")));
count = 0 ;
r1 = 0 ;
r3 = 0 ;
r2  = 0 ;
jb1.doClick();}
System.out.println("count is " + count) ;
if (count % 1 == 0 && (count % 2 !=0 && count % 3 != 0)){
if(r ==1 || r ==2 ){
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("e.jpg")));}
else
if(r ==1 || r ==3  ){
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
l1.setIcon(new ImageIcon(getClass().getResource("e.jpg")));
jt.setText("You may change or stick to your choice!");
r1 = 1 ;}
if(count%2 == 0 && count != 0){
if (r1 == 1 && r == 1){
jt.setText("You didnt change and you WON!");
l1.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r1 == 1 & r!= 1){
jt.setText("You didnt change and you lost!");
if(r == 2){
l3.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r == 3){
l2.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
}
if(r1 == 0 & r == 1){
jt.setText("You changed and you won");
if(r2 == 1){
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}
if(r3 == 1){
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}
}
if (r1 == 0 & r!=1){
jt.setText("You changed and you lost");
if(r2 == 1){
l3.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r3 == 1){
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}


}


}
// TODO add your handling code here:
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
count = count+ 1 ;
if (count % 3 == 0){
l1.setIcon(new ImageIcon(getClass().getResource("qm.png")));
l3.setIcon(new ImageIcon(getClass().getResource("qm.png")));
l2.setIcon(new ImageIcon(getClass().getResource("qm.png")));
count = 0 ;
r1 = 0 ;
r3 = 0 ;
r2  = 0 ;
jb1.doClick();
}
System.out.println("count is " + count) ;
if (count % 1 == 0 && (count % 2 !=0 && count % 3 != 0)){
if(r == 3 || r ==2 ){
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("e.jpg")));}
else
if(r ==1 || r ==3 ){
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("e.jpg")));}
jt.setText("You may change or stick to your choice!");
r3 = 1 ;}
if(count%2 == 0 && count != 0){
if (r3 == 1 && r == 3){
jt.setText("You didnt change and you WON!");
l2.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r3 == 1 & r!= 3){
jt.setText("You didnt change and you lost!");
if(r == 2){
l3.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r == 1){
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}
}
if(r3 == 0 & r == 3){
jt.setText("You changed and you won");
if(r2 == 1){
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}
if(r1== 1){
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}

}

if (r3 == 0 & r!=3){
jt.setText("You changed and you lost");
if(r2 == 1){
l3.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r1 == 1){
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}

}



}   // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
 count = count+ 1 ;
if (count % 3 == 0){
l1.setIcon(new ImageIcon(getClass().getResource("qm.png")));
l3.setIcon(new ImageIcon(getClass().getResource("qm.png")));
l2.setIcon(new ImageIcon(getClass().getResource("qm.png")));
count = 0 ;
r1 = 0 ;
r3 = 0 ;
r2  = 0 ;
jb1.doClick();
}
System.out.println("count is " + count) ;
if (count % 1 == 0 && (count % 2 !=0 && count % 3 != 0)){
if(r == 3 || r ==2 ){
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l3.setIcon(new ImageIcon(getClass().getResource("e.jpg")));}
else
if(r ==1 || r ==2 ){
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
l3.setIcon(new ImageIcon(getClass().getResource("e.jpg")));
jt.setText("You may change or stick to your choice!");
r2 = 1 ;}
if(count%2 == 0 && count != 0){
if (r2 == 1 && r == 2){
jt.setText("You didnt change and you WON!");
l3.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r2 == 1 & r!= 2){
jt.setText("You didnt change and you lost!");
if(r == 3){
l2.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r == 1){
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}
}
if(r2 == 0 & r == 2){
jt.setText("You changed and you won");
if(r3 == 1){
l2.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l3.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}
if(r1 == 1){
l1.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l3.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}
}

if (r2 == 0 & r!=2){
jt.setText("You changed and you lost");
if(r3 == 1){
l2.setIcon(new ImageIcon(getClass().getResource("1.jpg")));
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));}
if(r1 == 1){
l3.setIcon(new ImageIcon(getClass().getResource("2.jpg")));
l1.setIcon(new ImageIcon(getClass().getResource("1.jpg")));}

}



}    // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseClicked

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
l1.setIcon(new ImageIcon(getClass().getResource("qm.png")));
l3.setIcon(new ImageIcon(getClass().getResource("qm.png")));
l2.setIcon(new ImageIcon(getClass().getResource("qm.png")));
Random dice = new Random();
r = dice.nextInt(3)+1;
jt.setText("Chose one!");

System.out.println("r1 " + r1 + " r2 " + r2 + " r3 " + r3 + " r " + r );
r3 = 0 ;
r1 = 0 ;
r2 = 0;
count = 0;

// TODO add your handling code here:
    }//GEN-LAST:event_jb1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
double a = 10000;
try{
a = Double.parseDouble(t1.getText());}
catch(Exception e){
    System.out.println("Enter A Number in the box. Using 10000 tries.");
}
double win = 0;
int loss = 0 ;
for ( double x = 1 ;x <= a ;x = x + 1){
Random dice = new Random();
int s = dice.nextInt(3) + 1;
int d = 1 ;
if(s == 1 || s == 2 && s!=3 ){
d =  2 ;}
else if(s == 1 || s == 3 && s!=2 ){
d =  3 ;}
else{
loss = loss + 1;
continue ;}
if ( d == s){
win = win + 1;}
else if( d != s){
loss = loss + 1;}
}
System.out.println("After\t" + a + "\ttries.");
System.out.println("No of wins " + win + " No of losses " + loss);
double percent = (win / a )  ;
System.out.println("Win Percent " + percent);
t1.setText("Win/Loss Percent: " +percent);


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monty_Hall_Problem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb1;
    private javax.swing.JLabel jt;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}
